services:
  db:
    image: postgres:16
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: job_hunter_bot
        PGDATA: /var/lib/postgresql/data
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: 