# fly.toml app configuration file generated for vacancy-hunter on 2024-08-25T15:56:24+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vacancy-hunter'
primary_region = 'otp'

[build]
  [build.args]
    GO_VERSION = '1.23.0'

[env]
  PORT = '8080'
  TELEGRAM_BOT_TOKEN = "7028281349:AAFQBOy6gHSDaESyPWYOktrPqLugprIkdiU"
  FETCH_INTERVAL = "10m"
  NOTIFICATION_INTERVAL = "1m"
  FILTER_KEYWORDS = "Golang, Go, golang, go, Backend, Back-end"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
